add composer update to gitpod task

diff --git a/.gitpod.yml b/.gitpod.yml
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -11,3 +11,6 @@ tasks:
       echo SQL_NAME="localhost" > web/.env
       echo SQL_USER="root" >> web/.env
       echo SQL_PASSWORD="" >> web/.env
+    command: |
+      composer update
+      test $? -eq 0 && clear || echo "Composer update failed"
